Evr user refact
Sintrop/SAT-core-contracts pull request #40
Opened 2022-05-14 11:08 UTC by everson-ever

2022-05-19 16:43 UTC, everson-ever commented on contracts/Sintrop.sol
> +    // activists[msg.sender].recentInspection = true;
Vou remover comentário que ficou e verificar se deixei passar mais algum

2022-05-19 18:13 UTC, rav-andre requested changes

2022-05-19 21:38 UTC, everson-ever commented on contracts/Callable.sol
> +  function newAllowedCaller(address allowed) public onlyOwner {
@rav-andre A autorização deve ser para o endereço do contrato. Vc deve pegar o endereço do ProducerContract e registrar ele no UserContract

2022-05-19 21:42 UTC, everson-ever commented on contracts/ProducerContract.sol
> +  function recentInspection(address addr, bool state) public mustBeAllowedCaller {
@rav-andre recentInspection é apenas um atributo que vai dizer se o produtor ou ativista tem alguma inspeção em aberto.

`ESSA FUNÇÃO NÃO É A QUE FAZ INSPEÇÃO`

No caso do `produtor`, ele vai ter uma inspeção em aberto quando ele requisitar uma inspeção e aquele inspeção não foi inspecionada ainda

No caso do ativista, ele vai ter uma inspeção em aberto quando ele aceitar uma inspeção e não realizou ela ainda

2022-05-19 22:45 UTC, rav-andre commented on contracts/ProducerContract.sol
> +  function recentInspection(address addr, bool state) public mustBeAllowedCaller {
Beleza entendi.

2022-05-19 22:46 UTC, rav-andre commented on contracts/Callable.sol
> +  function newAllowedCaller(address allowed) public onlyOwner {
Entendi. Vou testar aqui novamente e retorno assim que finalizar.

2022-05-20 13:43 UTC, rav-andre commented on contracts/Callable.sol
> +  function newAllowedCaller(address allowed) public onlyOwner {
No novo teste segui os seguintes passos com sucesso:
1) Deploy user contract
2) Deploy producerContract passando o endereço do userContract
3) Deploy activistContract passando o endereço do userContract
4) Deploy sintropContract passando os endereços do producerContract e activistContract.
![image](https://user-images.githubusercontent.com/79549809/169538008-0e314adb-ecf9-4cf0-b234-b68e26bfbc52.png)

5) Ao clicar pra adicionar o endereço do ProducerContract pra registrar ele no UserContract, em um primeiro momento mesmo fazendo isso com a carteira owner o sistema não autorizou. Em seguida chamei o método newAllowedCaller pela carteira owner e dando autorização para o owner fazer e funcionou.
![image](https://user-images.githubusercontent.com/79549809/169538763-3ca2eb23-41b0-4de9-9bbe-475c63561fa4.png)

Porém achei um tanto quanto estranho a carteira do owner dar autorização pra ela mesmo. Se isso fosse direto já para o owner evitaria uma transação.

6) Adicionar o endereço do ProducerContract e registrar no userContract. 
![image](https://user-images.githubusercontent.com/79549809/169539059-6fbec17c-d2ee-4f9a-9aaf-94484e8d692a.png)

7) Mesmo procedimento anterior registrar o endereço ActivistContract no UserContract.

E pronto, finalizando esses passos acredito que o contrato estaria pronto para ser utilizado no processo de registro de usuários.

-----
Agora para o registro de um novo usuário, alternei a carteira para uma carteira de usuário que não seja o owner.
E registrei alguns usuários com sucesso.

![image](https://user-images.githubusercontent.com/79549809/169540532-8668bd8d-b2aa-4f36-90e6-54d080dcfa49.png)

Acredito que está funcionando!!

Depois testei para os ativistas e deu o mesmo erro que estava tendo de not allowed caller mas vou revisar aqui que devo ter feito algum processo equivocado.

2022-05-21 11:04 UTC, everson-ever commented on contracts/Sintrop.sol
> +    // activists[msg.sender].recentInspection = true;
Feito!

2022-05-21 11:16 UTC, everson-ever commented on contracts/Callable.sol
> +  function newAllowedCaller(address allowed) public onlyOwner {
@rav-andre As permissões para cadastro de um novo usuário devem sempre ser dadas aos contratos que cuidam do registro de usuários. Ou seja ProducerContract e ActivistContract. 

Dar permissão pra o Owner cadastrar um novo produtor ou ativista não faria sentido, pois já temos contratos que fazem isso e deixam as pessoas se cadastrarem por si só.

A ideia do Owner é gerenciar todo o sistema, onde ele ganha permissão pra por exemplo dizer qual é o contrato que pode cadastrar usuário. Um exemplo é o caso de dar permissão para o ProducerContract poder cadastrar produtores no sistema no UserContract.

Para o owner dar permissão para outros contratos, ou seja chamando o método `newAllowedCaller` ele deve conseguir chamar com sucesso, pois esse método só é acessível para o owner;

2022-05-21 13:22 UTC, rav-andre approved these changes

2022-05-21 20:34 UTC, merged